### ISSUE TITLE
how to do it

### ISSUE THREAD

**Issue by fulige18** [1nfiniteloop/json-bookmarks#2]
Hello developer, thank you very much for the plug-in you provided. It is the best plug-in so far, but I don't quite understand. How to replace the replacement here in the description? Can you be more specific. Thanks a lot, I don't know much about the code。
——————————————————————————————————————————————————————
Substituting "Bookmarks Toolbar" in Mozilla Firefox and "Bookmarks bar" in Chrome with ${BOOKMARKS_BAR}.
Substituting "Bookmarks Menu" in Mozilla Firefox and "Other bookmarks" in Chrome with ${BOOKMARKS_MENU}.

**Comment by fulige18** [comment]
To add: the export is normal, but the import keeps reporting an error.
![微信图片_20220412150012](https://user-images.githubusercontent.com/100845677/162899920-cd957311-20e3-413c-9d5f-edfd3ddb4090.png)

**Comment by 1nfiniteloop** [comment]
Hi,
The plugin itself will handle the substitution of the placeholders, there is no need to manually substitute them yourself. The error message seem to indicate that the bookmark path is faulty. Can you narrow down and share what bookmark is causing this error? Does it occur for all your bookmarks? The plugin will also print debug logs in the browser's development console that might help if you share. Additionally:
- What version of the plugin are you using? What version of the json bookmarks file?
- What browser are you importing & exporting from?

**Comment by fulige18** [comment]
[bookmarks_2022_4_28 (5).zip](https://github.com/1nfiniteloop/json-bookmarks/files/8581139/bookmarks_2022_4_28.5.zip)
I have tried bookmarks of various structures, such as the first-level directory, the second-level directory, and the root directory, but they cannot be imported normally. Attached is one of the bookmarks I tested。
1. I use the latest version of the plugin submitted by you on github. The json file is exported with the plugin and then imported back
2.  3. chrome browser

**Comment by 1nfiniteloop** [comment]
Could you also please share the exported json bookmarks file with these bookmarks?

**Comment by fulige18** [comment]
of cours
[bookmarks.v2 (3).zip](https://github.com/1nfiniteloop/json-bookmarks/files/8587667/bookmarks.v2.3.zip)
e

**Comment by 1nfiniteloop** [comment]
The problem is on the export rather than the import, the json file you sent are missing the substitutions of the built-in bookmark names. Example:

```json
{
  "version": 2,
  "reference": "https://github.com/1nfiniteloop/json-bookmarks",
  "bookmarks": [
    {
      "title": "kestrel-bookmark: 【红隼书签】一款简洁的在线书签导航网站。",
      "url": "https://gitee.com/zhanhongzhu/kestrel-bookmark",
      "path": "/${BOOKMARKS_BAR}/Imported/书签栏/稍后"
    },
...
```

I could not reproduce the issue but I'm pretty convinced I know the root cause: I've assumed that the built-in bookmark names "bookmarks bar" and "other bookmarks" is always in English. But these will most likely depend on the current system language.

Just to confirm, can you enter debug console "right mouse button" -> "Inspect" -> "tab Console" and type these into the debug console and let me know the result:
```javascript
let tree = await browser.bookmarks.getTree();
console.info(tree[0].children[0].title);
console.info(tree[0].children[1].title);
```
I expect you to get another result than in english:
```
Bookmarks bar
Other bookmarks
```

**Comment by 1nfiniteloop** [comment]
Latest add-on with the fix is available for evaluation in <https://github.com/1nfiniteloop/json-bookmarks/actions/runs/2253382026>
