### ISSUE TITLE
Support for V3 manifest format for chrome

### ISSUE THREAD

**Issue by dcardille** [1nfiniteloop/json-bookmarks#3]
It does appear that the extension works in chrome if manually loaded as unpacked, but it is removed with each chrome update.

I was looking into dragging the zip into the extension page directly, but chrome complains of the manifest format.

I am not informed enough to make the changes from manifest v2 to manifest v3.

Is this something you are capable of modifying for a next release and would you be willing to do this?

**Comment by 1nfiniteloop** [comment]
Hi, what does "chrome://version/" says? Can you attach screenshot or similar of the error?

**Comment by dcardille** [comment]
The version of chrome I am using ( current) on Windows 10
![image](https://github.com/1nfiniteloop/json-bookmarks/assets/4467049/b6576f70-d345-4a47-b01a-d886c4743a12)

The error I receive when I try to load the extension using drag of zip onto extension manager page ( chrome://extensions/ )
![image](https://github.com/1nfiniteloop/json-bookmarks/assets/4467049/6827e9a4-5d8a-4118-aceb-4a59befdcf54)

**Comment by dcardille** [comment]
To clarify, it _appears_ that the extension is removed each time chrome updates (quite regularly) and I need to re-install it.

It seems that the drag and drop install method does work ( and the extension works) , as well as the manual unzip and load unpacked method.
![image](https://github.com/1nfiniteloop/json-bookmarks/assets/4467049/63bd328b-aeea-4b3e-a9d8-d8df2d441d2e)

I am waiting for the next update to confirm it will be removed and I will need to re-installed manually again.
Thanks again for looking into this.

**Comment by 1nfiniteloop** [comment]
Bumping manifest version to 3. Please see pre-release under "Artifacts" in https://github.com/1nfiniteloop/json-bookmarks/actions/runs/7950553841 to confirm. Note that this version bump will result in separate packages for Mozilla and Chrome due to manifest incompatibility between them. 

Checking the effort to publish extension in Chrome store also..

**Comment by dcardille** [comment]
The previous version was "uninstalled" by the latest version update again.
I still do not understand why, but that appears to be the pattern,

I was able to download the artifact and install by dragging over the page
"chrome://extensions/"
I can confirm that the install did not produce any errors, and worked as
expected.

Unfortunate that the version for firefox and chrome are now different, but
I am crossing my fingers that this persists the next update.

Thanks for the efforts!

**Comment by 1nfiniteloop** [comment]
I've published this extension on Chrome Store now so you can install it from there instead: https://chromewebstore.google.com/detail/json-bookmarks/nalfimhmhafapgfcmajjjgeohmcnlfeh
