### ISSUE TITLE
I exported a json file from Session Buddy extension and tried json-bookmarks to import but failed

### ISSUE THREAD

**Issue by pmoncayo1012** [1nfiniteloop/json-bookmarks#4]
I exported a json file from Session Buddy extension and tried json-bookmarks to import but failed with the following error message:

"Supported version(s): 1,2 but chosen file has version: undefined"

**Comment by 1nfiniteloop** [comment]
I assume you mean extension "Session Buddy" in Chrome store to save/restore open tabs? This extension imports and exports bookmarks only, using a json format specific for this extension.
